// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package timestreamquery

import (
	"github.com/aws/aws-sdk-go/private/protocol"
)

const (

	// ErrCodeAccessDeniedException for service response error code
	// "AccessDeniedException".
	//
	// You are not authorized to perform this action.
	ErrCodeAccessDeniedException = "AccessDeniedException"

	// ErrCodeInternalServerException for service response error code
	// "InternalServerException".
	//
	// Timestream was unable to fully process this request because of an internal
	// server error.
	ErrCodeInternalServerException = "InternalServerException"

	// ErrCodeResultSizeExceededException for service response error code
	// "ResultSizeExceededException".
	//
	// The result size of this operation exceeded the specified limits.
	ErrCodeResultSizeExceededException = "ResultSizeExceededException"

	// ErrCodeThrottlingException for service response error code
	// "ThrottlingException".
	//
	// Too many requests were made by a user exceeding service quotas. The request
	// was throttled.
	ErrCodeThrottlingException = "ThrottlingException"

	// ErrCodeTimeoutException for service response error code
	// "TimeoutException".
	//
	// The query execution time has exceeded the max time allotted for this query.
	// For more information, see Quotas in the Timestream Developer Guide.
	ErrCodeTimeoutException = "TimeoutException"

	// ErrCodeValidationException for service response error code
	// "ValidationException".
	//
	// Invalid or malformed request.
	ErrCodeValidationException = "ValidationException"
)

var exceptionFromCode = map[string]func(protocol.ResponseMetadata) error{
	"AccessDeniedException":       newErrorAccessDeniedException,
	"InternalServerException":     newErrorInternalServerException,
	"ResultSizeExceededException": newErrorResultSizeExceededException,
	"ThrottlingException":         newErrorThrottlingException,
	"TimeoutException":            newErrorTimeoutException,
	"ValidationException":         newErrorValidationException,
}
