// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package timestreamquery

import (
	"github.com/aws/aws-sdk-go/private/protocol"
)

const (

	// ErrCodeAccessDeniedException for service response error code
	// "AccessDeniedException".
	//
	// You are not authorized to perform this action.
	ErrCodeAccessDeniedException = "AccessDeniedException"

	// ErrCodeConflictException for service response error code
	// "ConflictException".
	//
	// Unable to poll results for a cancelled query.
	ErrCodeConflictException = "ConflictException"

	// ErrCodeInternalServerException for service response error code
	// "InternalServerException".
	//
	// Timestream was unable to fully process this request because of an internal
	// server error.
	ErrCodeInternalServerException = "InternalServerException"

	// ErrCodeQueryExecutionException for service response error code
	// "QueryExecutionException".
	//
	// Timestream was unable to run the query successfully.
	ErrCodeQueryExecutionException = "QueryExecutionException"

	// ErrCodeThrottlingException for service response error code
	// "ThrottlingException".
	//
	// Too many requests were made by a user exceeding service quotas. The request
	// was throttled.
	ErrCodeThrottlingException = "ThrottlingException"

	// ErrCodeValidationException for service response error code
	// "ValidationException".
	//
	// Invalid or malformed request.
	ErrCodeValidationException = "ValidationException"
)

var exceptionFromCode = map[string]func(protocol.ResponseMetadata) error{
	"AccessDeniedException":   newErrorAccessDeniedException,
	"ConflictException":       newErrorConflictException,
	"InternalServerException": newErrorInternalServerException,
	"QueryExecutionException": newErrorQueryExecutionException,
	"ThrottlingException":     newErrorThrottlingException,
	"ValidationException":     newErrorValidationException,
}
